// Pokemon.java

// Generated by https://quicktype.io

package io.quicktype;

import java.util.Map;

public class Pokemon {
    private Ability[] abilities;
    private long baseExperience;
    private Species[] forms;
    private GameIndex[] gameIndices;
    private long height;
    private HeldItem[] heldItems;
    private long id;
    private boolean isDefault;
    private String locationAreaEncounters;
    private Move[] moves;
    private String name;
    private long order;
    private Species species;
    private Sprites sprites;
    private Stat[] stats;
    private Type[] types;
    private long weight;

    public Ability[] getAbilities() { return abilities; }
    public void setAbilities(Ability[] value) { this.abilities = value; }

    public long getBaseExperience() { return baseExperience; }
    public void setBaseExperience(long value) { this.baseExperience = value; }

    public Species[] getForms() { return forms; }
    public void setForms(Species[] value) { this.forms = value; }

    public GameIndex[] getGameIndices() { return gameIndices; }
    public void setGameIndices(GameIndex[] value) { this.gameIndices = value; }

    public long getHeight() { return height; }
    public void setHeight(long value) { this.height = value; }

    public HeldItem[] getHeldItems() { return heldItems; }
    public void setHeldItems(HeldItem[] value) { this.heldItems = value; }

    public long getID() { return id; }
    public void setID(long value) { this.id = value; }

    public boolean getIsDefault() { return isDefault; }
    public void setIsDefault(boolean value) { this.isDefault = value; }

    public String getLocationAreaEncounters() { return locationAreaEncounters; }
    public void setLocationAreaEncounters(String value) { this.locationAreaEncounters = value; }

    public Move[] getMoves() { return moves; }
    public void setMoves(Move[] value) { this.moves = value; }

    public String getName() { return name; }
    public void setName(String value) { this.name = value; }

    public long getOrder() { return order; }
    public void setOrder(long value) { this.order = value; }

    public Species getSpecies() { return species; }
    public void setSpecies(Species value) { this.species = value; }

    public Sprites getSprites() { return sprites; }
    public void setSprites(Sprites value) { this.sprites = value; }

    public Stat[] getStats() { return stats; }
    public void setStats(Stat[] value) { this.stats = value; }

    public Type[] getTypes() { return types; }
    public void setTypes(Type[] value) { this.types = value; }

    public long getWeight() { return weight; }
    public void setWeight(long value) { this.weight = value; }
}

// Ability.java

package io.quicktype;

import java.util.Map;

public class Ability {
    private Species ability;
    private boolean isHidden;
    private long slot;

    public Species getAbility() { return ability; }
    public void setAbility(Species value) { this.ability = value; }

    public boolean getIsHidden() { return isHidden; }
    public void setIsHidden(boolean value) { this.isHidden = value; }

    public long getSlot() { return slot; }
    public void setSlot(long value) { this.slot = value; }
}

// Species.java
// TODO: Aqui puse un TODO
package io.quicktype;

import java.util.Map;

public class Species {
    private String name;
    private String url;

    public String getName() { return name; }
    public void setName(String value) { this.name = value; }

    public String getURL() { return url; }
    public void setURL(String value) { this.url = value; }
}

// GameIndex.java

package io.quicktype;

import java.util.Map;

public class GameIndex {
    private long gameIndex;
    private Species version;

    public long getGameIndex() { return gameIndex; }
    public void setGameIndex(long value) { this.gameIndex = value; }

    public Species getVersion() { return version; }
    public void setVersion(Species value) { this.version = value; }
}

// HeldItem.java

package io.quicktype;

import java.util.Map;

public class HeldItem {
    private Species item;
    private VersionDetail[] versionDetails;

    public Species getItem() { return item; }
    public void setItem(Species value) { this.item = value; }

    public VersionDetail[] getVersionDetails() { return versionDetails; }
    public void setVersionDetails(VersionDetail[] value) { this.versionDetails = value; }
}

// VersionDetail.java

package io.quicktype;

import java.util.Map;

public class VersionDetail {
    private long rarity;
    private Species version;

    public long getRarity() { return rarity; }
    public void setRarity(long value) { this.rarity = value; }

    public Species getVersion() { return version; }
    public void setVersion(Species value) { this.version = value; }
}

// Move.java

package io.quicktype;

import java.util.Map;

public class Move {
    private Species move;
    private VersionGroupDetail[] versionGroupDetails;

    public Species getMove() { return move; }
    public void setMove(Species value) { this.move = value; }

    public VersionGroupDetail[] getVersionGroupDetails() { return versionGroupDetails; }
    public void setVersionGroupDetails(VersionGroupDetail[] value) { this.versionGroupDetails = value; }
}

// VersionGroupDetail.java

package io.quicktype;

import java.util.Map;

public class VersionGroupDetail {
    private long levelLearnedAt;
    private Species moveLearnMethod;
    private Species versionGroup;

    public long getLevelLearnedAt() { return levelLearnedAt; }
    public void setLevelLearnedAt(long value) { this.levelLearnedAt = value; }

    public Species getMoveLearnMethod() { return moveLearnMethod; }
    public void setMoveLearnMethod(Species value) { this.moveLearnMethod = value; }

    public Species getVersionGroup() { return versionGroup; }
    public void setVersionGroup(Species value) { this.versionGroup = value; }
}

// Sprites.java

package io.quicktype;

import java.util.Map;

public class Sprites {
    private String backDefault;
    private Object backFemale;
    private String backShiny;
    private Object backShinyFemale;
    private String frontDefault;
    private Object frontFemale;
    private String frontShiny;
    private Object frontShinyFemale;

    public String getBackDefault() { return backDefault; }
    public void setBackDefault(String value) { this.backDefault = value; }

    public Object getBackFemale() { return backFemale; }
    public void setBackFemale(Object value) { this.backFemale = value; }

    public String getBackShiny() { return backShiny; }
    public void setBackShiny(String value) { this.backShiny = value; }

    public Object getBackShinyFemale() { return backShinyFemale; }
    public void setBackShinyFemale(Object value) { this.backShinyFemale = value; }

    public String getFrontDefault() { return frontDefault; }
    public void setFrontDefault(String value) { this.frontDefault = value; }

    public Object getFrontFemale() { return frontFemale; }
    public void setFrontFemale(Object value) { this.frontFemale = value; }

    public String getFrontShiny() { return frontShiny; }
    public void setFrontShiny(String value) { this.frontShiny = value; }

    public Object getFrontShinyFemale() { return frontShinyFemale; }
    public void setFrontShinyFemale(Object value) { this.frontShinyFemale = value; }
}

// Stat.java

package io.quicktype;

import java.util.Map;

public class Stat {
    private long baseStat;
    private long effort;
    private Species stat;

    public long getBaseStat() { return baseStat; }
    public void setBaseStat(long value) { this.baseStat = value; }

    public long getEffort() { return effort; }
    public void setEffort(long value) { this.effort = value; }

    public Species getStat() { return stat; }
    public void setStat(Species value) { this.stat = value; }
}

// Type.java

package io.quicktype;

import java.util.Map;

public class Type {
    private long slot;
    private Species type;

    public long getSlot() { return slot; }
    public void setSlot(long value) { this.slot = value; }

    public Species getType() { return type; }
    public void setType(Species value) { this.type = value; }
}
